# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('ingredient_name',)},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('pub_date',)},
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
    ]
