# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meal-tracker-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for meal-tracker-ios
    pod 'Starscream','~> 3.0.4'
    pod 'MessageKit','~> 0.13.1'
    pod 'Alamofire','~> 4.7.0'

end
